config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :tasks
  end
  devise_for :users
  root to: "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  belongs_to :user

  def badge_color
    case status
    when 'not-started'
      'secondary'
    when 'in-progress'
      'info'
    when 'complete'
      'success'
    end
  end

  def status
    return 'not-started' if tasks.none?
    if tasks.all? { |task| task.complete? } 
      'complete'
    elsif tasks.any? { |task| task.in_progress? || task.complete? }
      'in-progress'
    else
      'not-started'
    end
  end

  def percent_complete
    return 0 if tasks.none?
    ((total_complete.to_f / total_tasks) * 100).round
  end

  def total_complete
    tasks.select { |task| task.complete? }.count
  end

  def total_tasks
    tasks.count
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  validates :status, inclusion: { in: ['not-started', 'in-progress', 'complete'] }

  STATUS_OPTIONS = [
    ['Not started', 'not-started'],
    ['In progress', 'in-progress'],
    ['Complete', 'complete']
  ]

  def badge_color
    case status
    when 'not-started'
      'secondary'
    when 'in-progress'
      'info'
    when 'complete'
      'success'
    end
  end

  def complete?
    status == 'complete'
  end

  def in_progress?
    status == 'in-progress'
  end

  def not_started?
    status == 'not-started'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1 or /projects/1.json
  def show
    @task = @project.tasks.build
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build 
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET projects/1/tasks
  def index
    @tasks = @project.tasks
  end

  # GET projects/1/tasks/1
  def show
  end

  # GET projects/1/tasks/new
  def new
    @task = @project.tasks.build
  end

  # GET projects/1/tasks/1/edit
  def edit
  end

  # POST projects/1/tasks
  def create
    @task = @project.tasks.build(task_params)

    if @task.save
      redirect_to(@task.project)
    else
      render action: 'new'
    end
  end

  # PUT projects/1/tasks/1
  def update
    if @task.update_attributes(task_params)
      redirect_to(@task.project)
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/tasks/1
  def destroy
    @task.destroy

    redirect_to @project
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:project_id])
    end

    def set_task
      @task = @project.tasks.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:name, :description, :status, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bd-light">
    <div class="container pt-5">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div> 

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%= link_to 'Back', @project, class: 'btn btn-secondary mb-3' %>
<div class="card">
  <div class="card-body">
    <h2 class="card-title mb-4">
      <span>Editing Project </span> 
    </h2>

    <%= render 'form', project: @project %>   
  </div>
</div>

app/views/projects/index.html.erb
<div class="card">
  <div class="card-body">
    <h2 class="card-title d-flex justify-content-between mb-4">
      <span> Projects </span> 
      <%= link_to 'New Project', new_project_path, class: 'btn btn-primary' %>
    </h2>

    <% @projects.each do |project| %>
      <%= link_to project, class: 'text-decoration-none' do %>
        <div class="card project-card mb-3">
          <div class="card-body">
            <div class="mb-3" > 
              <span class="badge badge-<%= project.badge_color %>">
                <%= project.status %>              
              </span>
              <span class="text-secondary">
                <small>
                  <%= project.percent_complete %>% complete 
                  (<%=project.total_complete %>/<%= project.total_tasks %> tasks)
                </small>
              </span>
            </div>
            <h5 class="card-title text-dark"><b><%= project.name %></b></h5>
            <p class="text-secondary"> <%= project.description %> </p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<%= link_to 'Back', projects_path, class: 'btn btn-secondary mb-3' %>
<div class="card">
  <div class="card-body">
    <h2 class="card-title mb-4">
      <span>New Project </span> 
    </h2>

      <%= render 'form', project: @project %>
  </div>
</div>

app/views/projects/show.html.erb
<%= link_to 'Back', projects_path, class: 'btn btn-secondary mb-3' %>

<div class="card">
  <div class="card-body">
    <h2 class="card-title d-flex justify-content-between mb-4">
      <span> <%= @project.name %> </span> 
      <div>
        <%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-warning' %>
        <%= link_to 'Destroy', @project, method: :delete, class: 'btn btn-danger',
          data: { confirm: 'Are you sure?' } %>
      </div>
    </h2>

    <div class="mb-4">
      <h6>Add task</h6>
      <%= form_for([@task.project, @task]) do |f| %>
        <% if @task.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

            <ul>
            <% @task.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <%= f.hidden_field :status, value: 'not-started' %>

        <div class="input-group">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Enter task name...' %>
          <div class="input-group-append">
            <%= f.submit class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>

    <h4> Tasks </h4>
    <% @project.tasks.each do |task| %>
      <% if task.persisted? %>
        <div class="card mb-3">
          <div class="card-body">
            <div class="d-flex justify-content-between">
              <span class="badge badge-<%= task.badge_color %> mb-3"> <%= task.status %> </span>
              <div>
                <%= link_to 'Edit', edit_project_task_path(task.project, task), class: 'btn btn-light btn-sm' %>
                <%= link_to 'Destroy', [task.project, task], method: :delete, data: { 
                  confirm: 'Are you sure?' }, class: 'btn btn-dark btn-sm' %>
              </div>
            </div>
            <h5 class="card-title mb-2"> 
              <span> <%= task.name %>  </span>
            </h5>
            <p> <%= task.description %> </p>
          </div>
        </div>
      <% end %>  
    <% end %>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_for([@task.project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br />
    <%= f.text_area :description , class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :status %><br />
    <%= f.select :status, Task::STATUS_OPTIONS, {}, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= link_to 'Back', @project, class: 'btn btn-secondary mb-3' %>
<div class="card">
  <div class="card-body">
    <h2 class="card-title mb-4">
      <span>Editing Task </span> 
    </h2>

    <%= render 'form' %>   
  </div>
</div>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Status</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.description %></td>
    <td><%= task.status %></td>
    <td><%= task.project %></td>
    <td><%= link_to 'Show', [task.project, task] %></td>
    <td><%= link_to 'Edit', edit_project_task_path(task.project, task) %></td>
    <td><%= link_to 'Destroy', [task.project, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_project_task_path(params[:project_id]) %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', project_tasks_path(@task.project) %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Project:</b>
  <%= @task.project %>
</p>


<%= link_to 'Edit', edit_project_task_path(@task.project, @task) %> |
<%= link_to 'Back', project_tasks_path(@task.project) %>